version = "1.1.16"

[format]
dedup = true
dedup_inactive_fullscreen = false
delim = " "
client = "{icon} "
client_active = "<span color=\"#c6a0f6\">{icon}</span>"
workspace = "{id}: {clients}  Â­" # invisible unicode char after spaces to keep them from being trimmed ğŸ˜­
workspace_empty = "{id}: ó°„°  Â­"
client_dup = "{icon}{counter_sup}{delim}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
client_fullscreen = "[{icon} ]{delim}"

[class_active]
DEFAULT="ï™"

[title_in_class."(firefox|librewolf|chrom.*)"]
"(?i)youtube" = "ï…ª"
"(?i)twitch" = "ï‡¨"

[class]
DEFAULT = "ï™"

# browsers
"(?i)firefox" = "ï‰©"
"(?i)librewolf" = "ï‰©"
chromium = "ï‰¨"

# terminals
"(?i)kitty" = "ï„ "
"(?i)alacritty" = "ï„ "

calibre-gui = "ï€­"

# image stuff
"Gimp-2.10" = "ï‡¼"
darktable = "ï‚ƒ"
krita = "ï‡¼"
"org.inkscape.Inkscape" = "ï‡¼"

swappy = "ï€¾"

# editors
code = "ï„¡"
code-oss = "ï„¡"
code-url-handler = "ï„¡"
"jetbrains-studio" = "ï…»" # is actually android studio
"(?i)waydroid.*" = "ï…»"
obsidian = "ó° ®"
"Arduino IDE" = "ï‹"
"org.kde.kate" = "ó±©¼"

# chat
discord = "ï‡¿"
vesktop = "ï‚†"
element = "ï‚†"
cinny = "ï‚†"
wasistlos = "ïˆ²"
"teams-for-linux" = "ó°Š»"

# gaming
steam = "ï†¶"
itch = "ï„›"
"Minecraft.*" = "ï†²"
"org.prismlauncher.PrismLauncher" = "ó°³"

# libreoffice
libreoffice-calc = "ï‡ƒ"
libreoffice-impress = "ï‡„"
libreoffice-startcenter = "ï‡‚"
libreoffice-writer = "ï‡‚"

# video
mpv = "ï‹"
vlc = "ï…„"
"com.obsproject.Studio" = "ï€½"

# music
spotify = "ï†¼"
"musicbee.exe" = "ï€"
"com.github.th_ch.youtube_music" = "ï€"

# email
thunderbird = "ï¯"
neomutt = "ï¯"

# file managers
dolphin = "ï„•"
"org.kde.gwenview" = "ï€¾"

# other
waypaper = "ï€¾"
Bitwarden = "ï‚„"
"Mullvad VPN" = "ï€£"

nm-connection-editor = "ïƒ¨"
org-ksnip-ksnip = "ï¥"
pavucontrol = "ïµ"
wire = "ó±™³"
wireshark-gtk = "ó±™³"

[exclude]
"" = "^$" # prevent displaying clients with empty class
